version: '3.1'

volumes:
  mysql_data: {}

services:
  node-graphql:
    build: .
    depends_on:
     - mysql_server
    ports:
     - 4000:4000
    network_mode: 'host'


  mysql_server:
    image: mysql
    container_name: mysql-server
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_DATABASE=api_node_demo"
      - "MYSQL_PASSWORD=root"
    volumes:
     - mysql_data:/var/lib/mysqlql/data
    ports:
      - 3306:3306
    network_mode: 'host'

